### PR TITLE
Add item disappears v2

### PR DESCRIPTION
**Pull request by katsuya94**

### CODE REVIEW

**Comment by kapil1garg** [comment]
LGTM. Only one that fails is the one you marked as failing

**Comment by pooja335** [comment]
my only issue is that if i have more than 4ish items, i get a weird rendering thing that only goes away when i touch the screen

**Comment by kapil1garg** [comment]
@pooja335 How did you generate that issue? I'm trying to replicate on iOS but I dont see it happening

**Comment by pooja335** [comment]
when i entered in the 4th or 5th item, just normally and then pressed enter, the keyboard goes away like it's supposed to but then the list has this rendering issue

**Comment by kapil1garg** [comment]
@pooja335 Ah, ok. I'm not seeing that bug on iOS. @katsuya94 are you getting it on your phone?

**Pull request merged**
